# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  comc1754netcorewebapp:
    image: comc1754netcorewebapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000
